// EAST Human View (C++-style pseudo source)
// Generated by src/east.py

namespace east_view /* source: test/py/case21_dict_in.py */ {

    // module body
// [5:0] function original=has_key_23
bool has_key_23(str k /* readonly */) {
        // [6:4]
        dict[str,int64] d /* type=dict[str,int64], borrow=value */ = {'a': 1, 'b': 2} /* type=dict[str,int64], borrow=value */;
// [7:4]
if (k in d /* type=bool, borrow=value */) {
            // [8:8]
            return True /* type=bool, borrow=value */;
        }
        else {
            // [10:8]
            return False /* type=bool, borrow=value */;
        }
    }

    // main guard body
    int64 __east_main_guard() {
        // [14:4]
        print(has_key_23('a')) /* type=None, borrow=value */;
        return 0;
    }

} // namespace east_view
