// EAST Human View (C++-style pseudo source)
// Generated by src/east.py

namespace east_view /* source: test/py/case30_slice_basic.py */ {

    // renamed_symbols
    //   main -> __pytra_main

    // module body
// [3:0] function original=main
None __pytra_main() {
        // renamed_symbols: {'main': '__pytra_main'}
        // [4:4]
        list[int64] nums /* type=list[int64], borrow=value */ = [10, 20, 30, 40, 50] /* type=list[int64], borrow=value */;
        // [5:4]
        str text /* type=str, borrow=value */ = 'abcdef' /* type=str, borrow=value */;
        // [7:4]
        list[int64] mid_nums /* type=list[int64], borrow=value */ = nums[1:4] /* type=list[int64], borrow=value */;
        // [8:4]
        str mid_text /* type=str, borrow=value */ = text[2:5] /* type=str, borrow=value */;
        // [10:4]
        print(mid_nums[0]) /* type=None, borrow=value */;
        // [11:4]
        print(mid_nums[2]) /* type=None, borrow=value */;
        // [12:4]
        print(mid_text) /* type=None, borrow=value */;
    }

    // main guard body
    int64 __east_main_guard() {
        // [16:4]
        main() /* type=None, borrow=value */;
        return 0;
    }

} // namespace east_view
