// EAST Human View (C++-style pseudo source)
// Generated by src/east.py

namespace east_view /* source: test/py/case26_dataclass.py */ {

    // module body
    // [5:0] from dataclasses import dataclass;
// [9:0] class original=Point99
struct Point99 {
        // [10:4]
        int64 x /* type=int64, borrow=value */ = /* none */;
        // [11:4]
        int64 y /* type=int64, borrow=value */ = 10 /* type=int64, borrow=value */;
// [13:4] function original=total
int64 total(Point99 self /* readonly */) {
            // [14:8]
            return self.x + self.y /* type=int64, borrow=value */;
        }
    };

    // main guard body
    int64 __east_main_guard() {
        // [18:4]
        Point99 p /* type=Point99, borrow=value */ = Point99(3) /* type=Point99, borrow=value */;
        // [19:4]
        print(p.total()) /* type=None, borrow=value */;
        return 0;
    }

} // namespace east_view
