// EAST Human View (C++-style pseudo source)
// Generated by src/east.py

namespace east_view /* source: test/py/case12_string_ops.py */ {

    // module body
// [5:0] function original=decorate
str decorate(str name /* readonly */) {
        // [6:4]
        str prefix /* type=str, borrow=value */ = '[USER] ' /* type=str, borrow=value */;
        // [7:4]
        str message /* type=str, borrow=value */ = prefix + name /* type=str, borrow=value */;
        // [8:4]
        return message + '!' /* type=str, borrow=value */;
    }

    // main guard body
    int64 __east_main_guard() {
        // [12:4]
        print(decorate('Alice')) /* type=None, borrow=value */;
        return 0;
    }

} // namespace east_view
