// EAST Human View (C++-style pseudo source)
// Generated by src/east.py

namespace east_view /* source: test/py/case01_add.py */ {

    // module body
// [5:0] function original=add
int64 add(int64 a /* readonly */, int64 b /* readonly */) {
        // [6:4]
        return a + b /* type=int64, borrow=value */;
    }

    // main guard body
    int64 __east_main_guard() {
        // [10:4]
        print(add(3, 4)) /* type=None, borrow=value */;
        return 0;
    }

} // namespace east_view
