// EAST Human View (C++-style pseudo source)
// Generated by src/east.py

namespace east_view /* source: test/py/case06_string.py */ {

    // module body
// [5:0] function original=greet
str greet(str name /* readonly */) {
        // [6:4]
        return 'Hello, ' + name /* type=str, borrow=value */;
    }

    // main guard body
    int64 __east_main_guard() {
        // [10:4]
        print(greet('Codex')) /* type=None, borrow=value */;
        return 0;
    }

} // namespace east_view
