// EAST Human View (C++-style pseudo source)
// Generated by src/east.py

namespace east_view /* source: test/py/case05_compare.py */ {

    // module body
// [5:0] function original=is_large
bool is_large(int64 n /* readonly */) {
// [6:4]
if (n >= 10 /* type=bool, borrow=value */) {
            // [7:8]
            return True /* type=bool, borrow=value */;
        }
        else {
            // [9:8]
            return False /* type=bool, borrow=value */;
        }
    }

    // main guard body
    int64 __east_main_guard() {
        // [13:4]
        print(is_large(11)) /* type=None, borrow=value */;
        return 0;
    }

} // namespace east_view
