// EAST Human View (C++-style pseudo source)
// Generated by src/east.py

namespace east_view /* source: test/py/case07_float.py */ {

    // module body
// [5:0] function original=half
float half(float x /* readonly */) {
        // [6:4]
        return x / 2.0 /* type=float, borrow=value */;
    }

    // main guard body
    int64 __east_main_guard() {
        // [10:4]
        print(half(5.0)) /* type=None, borrow=value */;
        return 0;
    }

} // namespace east_view
