// EAST Human View (C++-style pseudo source)
// Generated by src/east.py

namespace east_view /* source: test/py/case10_not.py */ {

    // module body
// [5:0] function original=invert
bool invert(bool flag /* readonly */) {
// [6:4]
if (not flag /* type=bool, borrow=value */) {
            // [7:8]
            return True /* type=bool, borrow=value */;
        }
        else {
            // [9:8]
            return False /* type=bool, borrow=value */;
        }
    }

    // main guard body
    int64 __east_main_guard() {
        // [13:4]
        print(invert(False)) /* type=None, borrow=value */;
        return 0;
    }

} // namespace east_view
