// EAST Human View (C++-style pseudo source)
// Generated by src/east.py

namespace east_view /* source: test/py/case31_math_extended.py */ {

    // renamed_symbols
    //   main -> __pytra_main

    // module body
    // [1:0] import math;
// [4:0] function original=main
None __pytra_main() {
        // renamed_symbols: {'main': '__pytra_main'}
        // [5:4]
        print(math.fabs(math.tan(0.0)) < 1e-12) /* type=None, borrow=value */;
        // [6:4]
        print(math.fabs(math.log(math.exp(1.0)) - 1.0) < 1e-12) /* type=None, borrow=value */;
        // [7:4]
        print(int(math.log10(1000.0))) /* type=None, borrow=value */;
        // [8:4]
        print(int(math.fabs(-3.5) * 10.0)) /* type=None, borrow=value */;
        // [9:4]
        print(int(math.ceil(2.1))) /* type=None, borrow=value */;
        // [10:4]
        print(int(math.pow(2.0, 5.0))) /* type=None, borrow=value */;
    }

    // main guard body
    int64 __east_main_guard() {
        // [14:4]
        main() /* type=None, borrow=value */;
        return 0;
    }

} // namespace east_view
