// EAST Human View (C++-style pseudo source)
// Generated by src/east.py

namespace east_view /* source: test/py/case29_int8.py */ {

    // renamed_symbols
    //   main -> __pytra_main

    // module body
// [2:0] function original=main
None __pytra_main() {
        // renamed_symbols: {'main': '__pytra_main'}
        // [4:4]
        int8 i /* type=int8, borrow=value */ = 1 /* type=int64, borrow=value */;
        // [5:4]
        print(i * 2) /* type=None, borrow=value */;
    }

    // main guard body
    int64 __east_main_guard() {
        // [8:4]
        main() /* type=None, borrow=value */;
        return 0;
    }

} // namespace east_view
