// EAST Human View (C++-style pseudo source)
// Generated by src/east.py

namespace east_view /* source: test/py/case04_assign.py */ {

    // module body
// [5:0] function original=square_plus_one
int64 square_plus_one(int64 n /* readonly */) {
        // [6:4]
        int64 result /* type=int64, borrow=value */ = n * n /* type=int64, borrow=value */;
        // [7:4]
        result /* type=int64, borrow=value */ /* Add */= 1 /* type=int64, borrow=value */;
        // [8:4]
        return result /* type=int64, borrow=value */;
    }

    // main guard body
    int64 __east_main_guard() {
        // [12:4]
        print(square_plus_one(5)) /* type=None, borrow=value */;
        return 0;
    }

} // namespace east_view
