// EAST Human View (C++-style pseudo source)
// Generated by src/east.py

namespace east_view /* source: test/py/case32_pathlib_extended.py */ {

    // renamed_symbols
    //   main -> __pytra_main

    // module body
    // [1:0] from pathlib import Path;
// [4:0] function original=main
None __pytra_main() {
        // renamed_symbols: {'main': '__pytra_main'}
        // [5:4]
        root /* type=Path, borrow=value */ = Path('test/obj/pathlib_case32') /* type=Path, borrow=value */;
        // [6:4]
        root.mkdir(parents=True, exist_ok=True) /* type=None, borrow=value */;
        // [8:4]
        child /* type=Path, borrow=value */ = root / 'values.txt' /* type=Path, borrow=value */;
        // [9:4]
        child.write_text('42') /* type=None, borrow=value */;
        // [11:4]
        print(child.exists()) /* type=None, borrow=value */;
        // [12:4]
        print(child.name) /* type=None, borrow=value */;
        // [13:4]
        print(child.stem) /* type=None, borrow=value */;
        // [14:4]
        print((child.parent / 'values.txt').exists()) /* type=None, borrow=value */;
        // [15:4]
        print(child.read_text()) /* type=None, borrow=value */;
    }

    // main guard body
    int64 __east_main_guard() {
        // [19:4]
        main() /* type=None, borrow=value */;
        return 0;
    }

} // namespace east_view
