"""toolchain2-compatible C++ header generation for runtime modules."""

from __future__ import annotations

from pytra.std.json import JsonVal

from toolchain2.emit.cpp.runtime_paths import collect_cpp_dependency_module_ids, cpp_include_for_module
from toolchain2.emit.cpp.types import cpp_param_decl, cpp_signature_type, collect_cpp_type_vars


def build_cpp_header_from_east3(
    module_id: str,
    east_doc: dict[str, JsonVal],
    *,
    rel_header_path: str,
    native_header_include: str = "",
) -> str:
    meta = east_doc.get("meta")
    meta_dict = meta if isinstance(meta, dict) else {}
    dep_ids = collect_cpp_dependency_module_ids(module_id, meta_dict)
    guard = _header_guard(rel_header_path)
    lines: list[str] = [
        "// AUTO-GENERATED by toolchain2/emit/cpp",
        "#ifndef " + guard,
        "#define " + guard,
        "",
        '#include "core/py_runtime.h"',
    ]

    seen: set[str] = {"core/py_runtime.h"}
    for dep_id in dep_ids:
        include_path = cpp_include_for_module(dep_id)
        if include_path == "" or include_path in seen:
            continue
        seen.add(include_path)
        lines.append('#include "' + include_path + '"')
    if native_header_include != "" and native_header_include not in seen:
        lines.append('#include "' + native_header_include + '"')
    lines.append("")

    body = east_doc.get("body")
    stmts = body if isinstance(body, list) else []
    class_names: list[str] = []
    for stmt in stmts:
        if not isinstance(stmt, dict) or _str(stmt, "kind") != "ClassDef":
            continue
        name = _str(stmt, "name")
        if name != "":
            class_names.append(name)
    if len(class_names) > 0:
        for name in class_names:
            lines.append("struct " + name + ";")
        lines.append("")
    for stmt in stmts:
        _emit_decl(lines, stmt)

    lines.extend([
        "",
        "#endif  // " + guard,
        "",
    ])
    return "\n".join(lines)


def _emit_decl(lines: list[str], stmt: JsonVal) -> None:
    if not isinstance(stmt, dict):
        return
    kind = _str(stmt, "kind")
    if kind in ("Import", "ImportFrom", "TypeAlias", "Pass"):
        return
    if kind == "Expr":
        value = stmt.get("value")
        if isinstance(value, dict) and value.get("kind") == "Constant" and isinstance(value.get("value"), str):
            return
    if kind in ("FunctionDef", "ClosureDef"):
        sig = _function_decl(stmt)
        if sig != "":
            lines.append(sig + ";")
        return
    if kind in ("AnnAssign", "Assign"):
        decl = _global_decl(stmt)
        if decl != "":
            lines.append(decl + ";")
        return
    if kind == "ClassDef":
        _emit_class_decl(lines, stmt)


def _function_decl(node: dict[str, JsonVal], *, owner_name: str = "", in_class: bool = False) -> str:
    name = _str(node, "name")
    if name == "":
        return ""
    params = _function_params(node)
    if name == "__init__" and owner_name != "":
        return owner_name + "(" + ", ".join(params) + ")"
    ret = cpp_signature_type(_return_type(node))
    prefix = ""
    static_prefix = ""
    suffix = ""
    if owner_name != "" and not in_class:
        prefix = owner_name + "::"
    if owner_name != "" and _has_decorator(node, "staticmethod") and in_class:
        static_prefix = "static "
    if owner_name != "" and not _has_decorator(node, "staticmethod") and name != "__init__" and not _function_self_mutates(node):
        suffix = " const"
    signature = static_prefix + ret + " " + prefix + name + "(" + ", ".join(params) + ")" + suffix
    template_prefix = _function_template_prefix(node)
    if template_prefix != "":
        return template_prefix + "\n" + signature
    return signature


def _global_decl(node: dict[str, JsonVal]) -> str:
    target = node.get("target")
    name = _target_name(target)
    if name == "":
        return ""
    decl_type = _str(node, "decl_type")
    if decl_type == "":
        decl_type = _str(node, "resolved_type")
    if decl_type == "":
        return ""
    return "extern " + cpp_signature_type(decl_type) + " " + name


def _emit_class_decl(lines: list[str], node: dict[str, JsonVal]) -> None:
    name = _str(node, "name")
    if name == "":
        return
    lines.append("struct " + name + " {")
    field_types = node.get("field_types")
    if isinstance(field_types, dict):
        for field_name, field_type in field_types.items():
            if isinstance(field_name, str) and isinstance(field_type, str):
                lines.append("    " + cpp_signature_type(field_type) + " " + field_name + ";")
    body = node.get("body")
    stmts = body if isinstance(body, list) else []
    for child in stmts:
        if not isinstance(child, dict) or _str(child, "kind") not in ("FunctionDef", "ClosureDef"):
            continue
        sig = _function_decl(child, owner_name=name, in_class=True)
        if sig != "":
            lines.append("    " + sig + ";")
    lines.append("};")
    lines.append("")


def _function_params(node: dict[str, JsonVal]) -> list[str]:
    arg_order = node.get("arg_order")
    arg_types = node.get("arg_types")
    arg_defaults = node.get("arg_defaults")
    arg_usage = node.get("arg_usage")
    params: list[str] = []
    order = arg_order if isinstance(arg_order, list) else []
    types = arg_types if isinstance(arg_types, dict) else {}
    defaults = arg_defaults if isinstance(arg_defaults, dict) else {}
    usage = arg_usage if isinstance(arg_usage, dict) else {}
    is_static = _has_decorator(node, "staticmethod")
    for arg in order:
        if not isinstance(arg, str):
            continue
        if arg == "self" and not is_static:
            continue
        arg_type = types.get(arg)
        resolved_type = arg_type if isinstance(arg_type, str) else "object"
        text = cpp_param_decl(resolved_type, arg, mutable=usage.get(arg) == "reassigned")
        default_node = defaults.get(arg)
        if isinstance(default_node, dict):
            default_text = _render_default_expr(default_node)
            if default_text != "":
                text += " = " + default_text
        params.append(text)
    return params


def _function_template_prefix(node: dict[str, JsonVal]) -> str:
    params = _function_template_params(node)
    if len(params) == 0:
        return ""
    return "template <" + ", ".join("class " + name for name in params) + ">"


def _function_template_params(node: dict[str, JsonVal]) -> list[str]:
    out: list[str] = []
    seen: set[str] = set()
    arg_types = node.get("arg_types")
    if isinstance(arg_types, dict):
        for arg_type in arg_types.values():
            if not isinstance(arg_type, str):
                continue
            for type_var in collect_cpp_type_vars(arg_type):
                if type_var not in seen:
                    seen.add(type_var)
                    out.append(type_var)
    for type_var in collect_cpp_type_vars(_return_type(node)):
        if type_var not in seen:
            seen.add(type_var)
            out.append(type_var)
    return out


def _function_self_mutates(node: dict[str, JsonVal]) -> bool:
    if _bool(node, "mutates_self"):
        return True
    arg_usage = node.get("arg_usage")
    if isinstance(arg_usage, dict):
        return arg_usage.get("self") == "reassigned"
    return False


def _render_default_expr(node: dict[str, JsonVal]) -> str:
    kind = _str(node, "kind")
    if kind == "Constant":
        value = node.get("value")
        if value is None:
            return "::std::nullopt"
        if isinstance(value, bool):
            return "true" if value else "false"
        if isinstance(value, int):
            return str(value)
        if isinstance(value, float):
            return repr(value)
        if isinstance(value, str):
            return _cpp_string(value)
        return ""
    if kind == "Name":
        name = _str(node, "id")
        if name == "None":
            return "::std::nullopt"
        if name == "True":
            return "true"
        if name == "False":
            return "false"
        return name
    if kind == "List":
        resolved_type = _str(node, "resolved_type")
        if resolved_type == "":
            resolved_type = "list[object]"
        items = node.get("elements")
        if not isinstance(items, list):
            items = []
        return cpp_signature_type(resolved_type) + "{" + ", ".join(
            _render_default_expr(item) for item in items if isinstance(item, dict)
        ) + "}"
    if kind == "Dict":
        resolved_type = _str(node, "resolved_type")
        if resolved_type == "":
            resolved_type = "dict[str,object]"
        entries = node.get("entries")
        parts: list[str] = []
        if isinstance(entries, list):
            for entry in entries:
                if isinstance(entry, dict):
                    parts.append("{" + _render_default_expr(entry.get("key")) + ", " + _render_default_expr(entry.get("value")) + "}")
        return cpp_signature_type(resolved_type) + "{" + ", ".join(parts) + "}"
    return ""


def _cpp_string(text: str) -> str:
    out: list[str] = ['"']
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        else:
            out.append(ch)
    out.append('"')
    return "str(" + "".join(out) + ")"


def _target_name(target: JsonVal) -> str:
    if isinstance(target, str):
        return target
    if isinstance(target, dict):
        return _str(target, "id")
    return ""


def _return_type(node: dict[str, JsonVal]) -> str:
    return_type = _str(node, "return_type")
    if return_type == "":
        return_type = _str(node, "returns")
    if return_type == "":
        return_type = "None"
    return return_type


def _has_decorator(node: dict[str, JsonVal], name: str) -> bool:
    decorators = node.get("decorators")
    if not isinstance(decorators, list):
        return False
    for decorator in decorators:
        if isinstance(decorator, str) and decorator == name:
            return True
    return False


def _header_guard(rel_header_path: str) -> str:
    parts: list[str] = []
    for ch in rel_header_path:
        if ch.isalnum():
            parts.append(ch.upper())
        else:
            parts.append("_")
    return "PYTRA_GEN_" + "".join(parts)


def _str(node: dict[str, JsonVal], key: str) -> str:
    value = node.get(key)
    return value if isinstance(value, str) else ""


def _bool(node: dict[str, JsonVal], key: str) -> bool:
    value = node.get(key)
    return value if isinstance(value, bool) else False
