"""Built-in container class declarations.

These are @extern class declarations — the actual implementations are
provided by each language's runtime. The resolve/compile pipeline reads
these declarations to determine:

- Method signatures (argument types, return types)
- Mutability (mut[T] annotation on self/arguments)
- Generic type parameters (@template)

Emitters do not read this file directly. They use EAST3 metadata
(borrow_kind, mutates_receiver, runtime_call, etc.) that resolve
derives from these declarations.
"""

from typing import TypeVar

T = TypeVar("T")
K = TypeVar("K")
V = TypeVar("V")


@extern
class list:
    @template
    def append(self: mut[list[T]], value: T) -> None: ...

    @template
    def extend(self: mut[list[T]], values: list[T]) -> None: ...

    @template
    def insert(self: mut[list[T]], index: int, value: T) -> None: ...

    @template
    def pop(self: mut[list[T]]) -> T: ...

    def clear(self: mut[list]) -> None: ...

    def reverse(self: mut[list]) -> None: ...

    def sort(self: mut[list]) -> None: ...

    @template
    def index(self: list[T], value: T) -> int: ...

    def __len__(self) -> int: ...


@extern
class dict:
    @template
    def get(self: dict[K, V], key: K, default: V) -> V: ...

    @template
    def keys(self: dict[K, V]) -> list[K]: ...

    @template
    def values(self: dict[K, V]) -> list[V]: ...

    @template
    def items(self: dict[K, V]) -> list[tuple[K, V]]: ...

    @template
    def pop(self: mut[dict[K, V]], key: K) -> V: ...

    @template
    def setdefault(self: mut[dict[K, V]], key: K, default: V) -> V: ...

    @template
    def update(self: mut[dict[K, V]], other: dict[K, V]) -> None: ...

    def clear(self: mut[dict]) -> None: ...

    def __len__(self) -> int: ...


@extern
class set:
    @template
    def add(self: mut[set[T]], value: T) -> None: ...

    @template
    def discard(self: mut[set[T]], value: T) -> None: ...

    @template
    def remove(self: mut[set[T]], value: T) -> None: ...

    @template
    def update(self: mut[set[T]], other: set[T]) -> None: ...

    def clear(self: mut[set]) -> None: ...

    def __len__(self) -> int: ...


@extern
class str:
    def split(self, sep: str) -> list[str]: ...

    def join(self, iterable: list[str]) -> str: ...

    def strip(self) -> str: ...

    def lstrip(self) -> str: ...

    def rstrip(self) -> str: ...

    def replace(self, old: str, new: str) -> str: ...

    def startswith(self, prefix: str) -> bool: ...

    def endswith(self, suffix: str) -> bool: ...

    def upper(self) -> str: ...

    def lower(self) -> str: ...

    def find(self, sub: str) -> int: ...

    def rfind(self, sub: str) -> int: ...

    def index(self, sub: str) -> int: ...

    def isdigit(self) -> bool: ...

    def isalpha(self) -> bool: ...

    def isalnum(self) -> bool: ...

    def isspace(self) -> bool: ...

    def count(self, sub: str) -> int: ...

    def __len__(self) -> int: ...


@extern
class bytearray:
    def append(self: mut[bytearray], value: int) -> None: ...

    def extend(self: mut[bytearray], values: bytearray) -> None: ...

    def pop(self: mut[bytearray]) -> int: ...

    def clear(self: mut[bytearray]) -> None: ...

    def __len__(self) -> int: ...
