# pytra: builtin-declarations
"""コンテナ型の dunder + メソッド宣言。

resolve がメソッドシグネチャ + meta.extern_v2 を参照して型解決する。emit 対象外。
@template でクラスレベル型パラメータを宣言する。
引数の型は exact match（暗黙変換なし）。

spec: docs/ja/spec/spec-builtin-functions.md §4, §10
"""

from pytra.std import template, runtime


# ---------------------------------------------------------------------------
# Iterable[T] — for ループの __iter__ 戻り値型
# ---------------------------------------------------------------------------

@template("T")
class Iterable:
    ...


# ---------------------------------------------------------------------------
# §4.1 list
# ---------------------------------------------------------------------------

@template("T")
@runtime("pytra.core")
class list:
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...
    def __bool__(self) -> bool: ...
    def __iter__(self) -> Iterable[T]: ...
    def append(self, x: T) -> None: ...
    def extend(self, x: list[T]) -> None: ...
    def pop(self, index: int = -1) -> T: ...
    def insert(self, index: int, x: T) -> None: ...
    def remove(self, x: T) -> None: ...
    def clear(self) -> None: ...
    def reverse(self) -> None: ...
    def sort(self) -> None: ...
    def copy(self) -> list[T]: ...
    def index(self, x: T) -> int: ...
    def count(self, x: T) -> int: ...


# ---------------------------------------------------------------------------
# §4.2 str
# ---------------------------------------------------------------------------

@runtime("pytra.core")
class str:
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...
    def __bool__(self) -> bool: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def upper(self) -> str: ...
    def lower(self) -> str: ...
    def strip(self) -> str: ...
    def lstrip(self) -> str: ...
    def rstrip(self) -> str: ...
    def split(self, sep: str = " ") -> list[str]: ...
    def join(self, parts: list[str]) -> str: ...
    def startswith(self, prefix: str) -> bool: ...
    def endswith(self, suffix: str) -> bool: ...
    def find(self, sub: str) -> int: ...
    def rfind(self, sub: str) -> int: ...
    def replace(self, old: str, new: str) -> str: ...
    def isdigit(self) -> bool: ...
    def isalpha(self) -> bool: ...
    def isalnum(self) -> bool: ...
    def isupper(self) -> bool: ...
    def islower(self) -> bool: ...
    def zfill(self, width: int) -> str: ...
    def count(self, sub: str) -> int: ...


# ---------------------------------------------------------------------------
# §4.3 dict
# ---------------------------------------------------------------------------

@template("K", "V")
@runtime("pytra.core")
class dict:
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...
    def __bool__(self) -> bool: ...
    def keys(self) -> list[K]: ...
    def values(self) -> list[V]: ...
    def items(self) -> list[tuple[K, V]]: ...
    def get(self, key: K, default: V = None) -> V: ...
    def pop(self, key: K) -> V: ...
    def setdefault(self, key: K, default: V = None) -> V: ...
    def clear(self) -> None: ...
    def update(self, other: dict[K, V]) -> None: ...


# ---------------------------------------------------------------------------
# §4.4 set
# ---------------------------------------------------------------------------

@template("T")
@runtime("pytra.core")
class set:
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...
    def __bool__(self) -> bool: ...
    def add(self, x: T) -> None: ...
    def discard(self, x: T) -> None: ...
    def remove(self, x: T) -> None: ...
    def clear(self) -> None: ...
    def update(self, other: list[T]) -> None: ...
    def update(self, other: set[T]) -> None: ...


# ---------------------------------------------------------------------------
# §4.5 tuple
# ---------------------------------------------------------------------------

@runtime("pytra.core")
class tuple:
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...
    def __bool__(self) -> bool: ...
