#!/usr/bin/env python3
"""Guard generated-runtime passthrough naming policy for std/utils modules.

Policy:
- Canonical source of module basenames is `src/pytra/std/*.py` and `src/pytra/utils/*.py`.
- For migrated non-C++ backends, canonical generated lanes live under
  `src/runtime/<lang>/generated/std|utils/<module>.<ext>`.
- Legacy `src/runtime/<lang>/pytra-gen/**` is still scanned for backends that have not yet
  rolled over to the `generated/native` layout.
- Under `std` / `utils`, use passthrough module basenames only.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RUNTIME_ROOT = ROOT / "src" / "runtime"
PYTRA_STD_ROOT = ROOT / "src" / "pytra" / "std"
PYTRA_UTILS_ROOT = ROOT / "src" / "pytra" / "utils"
ALLOWLIST_PATH = ROOT / "tools" / "runtime_pytra_gen_naming_allowlist.txt"

TARGET_SUFFIXES = {
    ".c",
    ".cc",
    ".cpp",
    ".cs",
    ".go",
    ".h",
    ".hpp",
    ".java",
    ".js",
    ".kt",
    ".lua",
    ".nim",
    ".php",
    ".rb",
    ".rs",
    ".scala",
    ".swift",
    ".ts",
}


@dataclass(frozen=True)
class Finding:
    rel_path: str
    reason: str
    detail: str

    @property
    def key(self) -> str:
        return f"{self.rel_path}:{self.reason}"


def _collect_module_names(base: Path) -> set[str]:
    names: set[str] = set()
    if not base.exists():
        return names
    for p in sorted(base.glob("*.py")):
        if p.name == "__init__.py":
            continue
        if p.stem.endswith("_impl"):
            # *_impl remains a handwritten impl-boundary lane, not a generated passthrough name.
            continue
        names.add(p.stem)
    return names


def _iter_pytra_gen_files() -> list[Path]:
    out: list[Path] = []
    if not RUNTIME_ROOT.exists():
        return out
    for p in sorted(RUNTIME_ROOT.rglob("*")):
        if not p.is_file():
            continue
        if p.suffix.lower() not in TARGET_SUFFIXES:
            continue
        rel = "/" + str(p.relative_to(ROOT)).replace("\\", "/")
        if "/pytra-gen/" in rel:
            out.append(p)
            continue
        if rel.startswith("/src/runtime/east/"):
            continue
        if "/generated/" in rel:
            out.append(p)
            continue
    return out


def _to_rel(path: Path) -> str:
    return str(path.relative_to(ROOT)).replace("\\", "/")


def _collect_findings() -> list[Finding]:
    std_modules = _collect_module_names(PYTRA_STD_ROOT)
    utils_modules = _collect_module_names(PYTRA_UTILS_ROOT)

    findings: list[Finding] = []
    for path in _iter_pytra_gen_files():
        rel = _to_rel(path)
        parts = rel.split("/")
        lane = ""
        if "pytra-gen" in parts:
            lane = "pytra-gen"
        elif "generated" in parts:
            lane = "generated"
        if lane == "":
            continue
        i = parts.index(lane)
        if len(parts) <= i + 1:
            continue
        bucket = parts[i + 1]
        # generated lane 直下の README などは監査対象外。
        if bucket == "README.md":
            continue
        if bucket == "built_in":
            continue
        if bucket not in {"std", "utils"}:
            findings.append(
                Finding(
                    rel_path=rel,
                    reason="invalid_bucket",
                    detail=f"bucket={bucket} (expected: std|utils)",
                )
            )
            continue

        # `std/<file>` or `utils/<file>` のみ許可（ネスト禁止）。
        if len(parts) != i + 3:
            findings.append(
                Finding(
                    rel_path=rel,
                    reason="nested_path",
                    detail=f"path under {lane}/{bucket} must be one-level file",
                )
            )
            continue

        stem = path.stem
        expected = std_modules if bucket == "std" else utils_modules
        if stem not in expected:
            findings.append(
                Finding(
                    rel_path=rel,
                    reason="non_passthrough_name",
                    detail=f"module={stem} (allowed: {','.join(sorted(expected))})",
                )
            )
    uniq: dict[str, Finding] = {}
    for item in findings:
        uniq.setdefault(item.key, item)
    return sorted(uniq.values(), key=lambda x: x.key)


def _read_allowlist(path: Path) -> set[str]:
    if not path.exists():
        return set()
    out: set[str] = set()
    for row in path.read_text(encoding="utf-8").splitlines():
        line = row.strip()
        if line == "" or line.startswith("#"):
            continue
        out.add(line)
    return out


def _write_allowlist(path: Path, keys: list[str]) -> None:
    lines = [
        "# Auto-generated by tools/check_runtime_pytra_gen_naming.py --write-allowlist",
        "# key format: <repo-relative-path>:<reason>",
        "",
    ] + keys
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser(
        description="check generated runtime std/utils passthrough naming policy"
    )
    ap.add_argument(
        "--write-allowlist",
        action="store_true",
        help="overwrite allowlist with current findings",
    )
    args = ap.parse_args()

    findings = _collect_findings()
    key_map = {item.key: item for item in findings}
    keys = sorted(key_map.keys())

    if args.write_allowlist:
        _write_allowlist(ALLOWLIST_PATH, keys)
        print(
            "[OK] wrote allowlist:",
            ALLOWLIST_PATH.relative_to(ROOT),
            f"({len(keys)} entries)",
        )
        return 0

    allowed = _read_allowlist(ALLOWLIST_PATH)
    if len(allowed) == 0:
        if len(keys) == 0:
            print("[OK] runtime generated naming guard passed (no findings; allowlist empty)")
            return 0
        print(f"[FAIL] allowlist missing or empty: {ALLOWLIST_PATH.relative_to(ROOT)}")
        print("run: python3 tools/check_runtime_pytra_gen_naming.py --write-allowlist")
        return 1

    added = sorted(key for key in keys if key not in allowed)
    stale = sorted(key for key in allowed if key not in key_map)

    if len(added) > 0:
        print("[FAIL] generated runtime naming policy violations detected:")
        for key in added:
            item = key_map[key]
            print(f"  - {item.rel_path} [{item.reason}] {item.detail}")
        print("review and either fix paths/names or refresh allowlist:")
        print("  python3 tools/check_runtime_pytra_gen_naming.py --write-allowlist")
        return 1

    print("[OK] runtime generated naming guard passed")
    print(f"  tracked baseline findings: {len(keys)}")
    if len(stale) > 0:
        print(f"  note: stale allowlist entries: {len(stale)} (cleanup recommended)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
