#!/usr/bin/env python3
"""Guard against forbidden runtime implementation symbols in emitter sources.

Policy:
- `src/toolchain/emit/*/emitter/*.py` must not grow references to runtime
  implementation symbols (`__pytra_write_rgb_png`, etc.).
- Existing debt is tracked explicitly in an allowlist.
- Newly introduced references fail this check.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BACKENDS_ROOT = ROOT / "src" / "backends"
ALLOWLIST_PATH = ROOT / "tools" / "emitter_forbidden_runtime_symbols_allowlist.txt"

IGNORED_BACKENDS = {"common"}
FORBIDDEN_SYMBOLS = (
    "__pytra_grayscale_palette",
    "__pytra_save_gif",
    "__pytra_write_rgb_png",
)


@dataclass(frozen=True)
class Finding:
    rel_path: str
    line_no: int
    symbol: str
    snippet: str

    @property
    def key(self) -> str:
        return f"{self.rel_path}:{self.line_no}:{self.symbol}"


def _iter_emitter_files() -> list[Path]:
    files: list[Path] = []
    if not BACKENDS_ROOT.exists():
        return files
    for backend_dir in sorted(BACKENDS_ROOT.iterdir()):
        if not backend_dir.is_dir():
            continue
        if backend_dir.name in IGNORED_BACKENDS:
            continue
        emitter_dir = backend_dir / "emitter"
        if not emitter_dir.exists():
            continue
        for path in sorted(emitter_dir.rglob("*.py")):
            if path.is_file():
                files.append(path)
    return files


def _collect_findings() -> list[Finding]:
    findings: list[Finding] = []
    for path in _iter_emitter_files():
        rel_path = str(path.relative_to(ROOT))
        for line_no, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
            for symbol in FORBIDDEN_SYMBOLS:
                if symbol in raw:
                    findings.append(
                        Finding(
                            rel_path=rel_path,
                            line_no=line_no,
                            symbol=symbol,
                            snippet=raw.strip(),
                        )
                    )
    findings.sort(key=lambda item: item.key)
    return findings


def _read_allowlist(path: Path) -> set[str]:
    if not path.exists():
        return set()
    out: set[str] = set()
    for row in path.read_text(encoding="utf-8").splitlines():
        line = row.strip()
        if line == "" or line.startswith("#"):
            continue
        out.add(line)
    return out


def _write_allowlist(path: Path, keys: list[str]) -> None:
    header = [
        "# Auto-generated by tools/check_emitter_forbidden_runtime_symbols.py --write-allowlist",
        "# Emitter forbidden runtime-symbol baseline",
        "",
    ]
    path.write_text("\n".join(header + keys) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Guard forbidden runtime implementation symbols in emitter sources"
    )
    parser.add_argument(
        "--write-allowlist",
        action="store_true",
        help="overwrite allowlist with current findings",
    )
    args = parser.parse_args()

    findings = _collect_findings()
    keys = sorted(item.key for item in findings)
    finding_map = {item.key: item for item in findings}

    if args.write_allowlist:
        _write_allowlist(ALLOWLIST_PATH, keys)
        print(
            "[OK] wrote allowlist:",
            ALLOWLIST_PATH.relative_to(ROOT),
            f"({len(keys)} entries)",
        )
        return 0

    allowed = _read_allowlist(ALLOWLIST_PATH)
    if len(allowed) == 0:
        if len(keys) == 0:
            print("[OK] emitter forbidden-runtime-symbol guardrails passed (no findings; allowlist empty)")
            return 0
        print(f"[FAIL] allowlist missing or empty: {ALLOWLIST_PATH.relative_to(ROOT)}")
        print("run: python3 tools/check_emitter_forbidden_runtime_symbols.py --write-allowlist")
        return 1

    added = sorted(key for key in keys if key not in allowed)
    stale = sorted(key for key in allowed if key not in finding_map)

    if len(added) > 0:
        print("[FAIL] new forbidden runtime symbol reference(s) detected in emitter:")
        for key in added:
            finding = finding_map[key]
            print(f"  - {finding.rel_path}:{finding.line_no} [{finding.symbol}] {finding.snippet}")
        print("Move symbol resolution to IR/profile/runtime layer, then refresh allowlist only for intentional cleanup:")
        print("  python3 tools/check_emitter_forbidden_runtime_symbols.py --write-allowlist")
        return 1

    print("[OK] emitter forbidden-runtime-symbol guardrails passed")
    print(f"  tracked baseline findings: {len(keys)}")
    if len(stale) > 0:
        print(f"  note: stale allowlist entries: {len(stale)} (cleanup recommended)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
