#!/usr/bin/env python3
"""Build C++ sources generated by `py2cpp.py --multi-file`."""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

from cpp_runtime_deps import ROOT
from cpp_runtime_deps import collect_runtime_cpp_sources


def _load_manifest(path: Path) -> dict[str, object]:
    import json

    obj = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(obj, dict):
        raise RuntimeError("manifest must be JSON object")
    return obj


def _collect_sources(manifest: dict[str, object]) -> list[str]:
    modules_obj = manifest.get("modules")
    if not isinstance(modules_obj, list):
        raise RuntimeError("manifest.modules must be list")
    out: list[str] = []
    i = 0
    while i < len(modules_obj):
        ent = modules_obj[i]
        if isinstance(ent, dict):
            src = ent.get("source")
            if isinstance(src, str) and src != "":
                out.append(src)
        i += 1
    if len(out) == 0:
        raise RuntimeError("manifest has no module sources")
    return out


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("manifest", help="Path to multi-file manifest.json")
    ap.add_argument("-o", "--output", default="a.out", help="Output executable path")
    ap.add_argument("--std", default="c++20", help="C++ language standard")
    ap.add_argument("--opt", default="-O2", help="Optimization flag")
    args = ap.parse_args(argv)

    manifest_path = Path(args.manifest)
    if not manifest_path.exists():
        print(f"error: manifest not found: {manifest_path}", file=sys.stderr)
        return 1
    def _collect_generated_cpp_sources() -> list[str]:
        """Collect generated .cpp files that are actually referenced by module sources.

        Scans module sources for #include directives, resolves them against
        the generated directory, and links the corresponding .cpp if it exists.
        """
        gen_dir = os.environ.get("PYTRA_GENERATED_CPP_DIR", "work/out/_test_generated_cpp")
        gen_path = Path(gen_dir)
        if not gen_path.exists():
            return []
        import re as _re
        _inc_re = _re.compile(r'^\s*#include\s+"([^"]+)"', _re.MULTILINE)
        # Collect all #include targets from module sources
        included_headers: set[str] = set()
        for src_path in module_sources:
            p = Path(src_path)
            if p.exists():
                for inc in _inc_re.findall(p.read_text(encoding="utf-8")):
                    included_headers.add(inc)
        # Also scan include dir headers (transitive deps)
        if include_dir_path.exists():
            for hdr in include_dir_path.rglob("*.h"):
                for inc in _inc_re.findall(hdr.read_text(encoding="utf-8")):
                    included_headers.add(inc)
        needed: list[Path] = []
        seen: set[str] = set()
        for inc in sorted(included_headers):
            # Resolve against generated dir
            gen_file = gen_path / inc
            if gen_file.exists() and gen_file.suffix == ".h":
                cpp_file = gen_file.with_suffix(".cpp")
                if cpp_file.exists() and str(cpp_file) not in seen:
                    seen.add(str(cpp_file))
                    needed.append(cpp_file)
        # Also include native C++ implementations for extern runtime modules.
        native_cpp_root = Path("src/runtime/cpp")
        for subdir in ["std", "utils"]:
            native_dir = native_cpp_root / subdir
            if native_dir.exists():
                for cpp_file in sorted(native_dir.glob("*.cpp")):
                    gen_header = gen_path / subdir / cpp_file.with_suffix(".h").name
                    if gen_header.exists() and str(cpp_file) not in seen:
                        # Only include if a module actually references this header
                        header_ref = subdir + "/" + cpp_file.with_suffix(".h").name
                        if header_ref in included_headers:
                            seen.add(str(cpp_file))
                            needed.append(cpp_file)
        # type_id.cpp is always needed (provides py_tid_is_subtype etc.,
        # referenced from type_id_support.h via forward declarations).
        type_id_cpp = gen_path / "built_in" / "type_id.cpp"
        if type_id_cpp.exists() and str(type_id_cpp) not in seen:
            seen.add(str(type_id_cpp))
            needed.append(type_id_cpp)
        return [str(f) for f in needed if f.exists()]

    manifest = _load_manifest(manifest_path)
    module_sources = _collect_sources(manifest)

    include_dir_obj = manifest.get("include_dir")
    include_dir = include_dir_obj if isinstance(include_dir_obj, str) else str(manifest_path.parent / "include")
    include_dir_path = Path(include_dir)
    if not include_dir_path.is_absolute():
        include_dir_path = (manifest_path.parent / include_dir_path).resolve()

    cmd = [
        "g++",
        f"-std={args.std}",
        args.opt,
        "-I",
        "src",
        "-I",
        "src/runtime/cpp",
        "-I",
        "src/runtime/east",
        "-I",
        str(include_dir_path),
        "-I",
        os.environ.get("PYTRA_GENERATED_CPP_DIR", "work/out/_test_generated_cpp"),
        *module_sources,
        *collect_runtime_cpp_sources(module_sources, include_dir_path),
        *_collect_generated_cpp_sources(),
        "-o",
        args.output,
    ]
    p = subprocess.run(cmd)
    return int(p.returncode)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
