#!/usr/bin/env python3
"""Build C++ sources generated by `py2cpp.py --multi-file`."""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path

from cpp_runtime_deps import ROOT
from cpp_runtime_deps import collect_runtime_cpp_sources


def _load_manifest(path: Path) -> dict[str, object]:
    import json

    obj = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(obj, dict):
        raise RuntimeError("manifest must be JSON object")
    return obj


def _collect_sources(manifest: dict[str, object]) -> list[str]:
    modules_obj = manifest.get("modules")
    if not isinstance(modules_obj, list):
        raise RuntimeError("manifest.modules must be list")
    out: list[str] = []
    i = 0
    while i < len(modules_obj):
        ent = modules_obj[i]
        if isinstance(ent, dict):
            src = ent.get("source")
            if isinstance(src, str) and src != "":
                out.append(src)
        i += 1
    if len(out) == 0:
        raise RuntimeError("manifest has no module sources")
    return out


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("manifest", help="Path to multi-file manifest.json")
    ap.add_argument("-o", "--output", default="a.out", help="Output executable path")
    ap.add_argument("--std", default="c++20", help="C++ language standard")
    ap.add_argument("--opt", default="-O2", help="Optimization flag")
    args = ap.parse_args(argv)

    manifest_path = Path(args.manifest)
    if not manifest_path.exists():
        print(f"error: manifest not found: {manifest_path}", file=sys.stderr)
        return 1
    def _collect_generated_cpp_sources() -> list[str]:
        """Collect only the generated .cpp files that are actually #included by module sources."""
        gen_dir = os.environ.get("PYTRA_GENERATED_CPP_DIR", "out/_test_generated_cpp")
        gen_path = Path(gen_dir)
        if not gen_path.exists():
            return []
        # Include generated .cpp files needed for test compilation.
        # Only include files verified to compile correctly.
        # NOTE: Most generated std/*.cpp files have Object<T> migration
        # incompatibilities (py_repeat on str, expected primary-expression, etc.)
        # Only include files verified to compile correctly.
        needed = [
            gen_path / "utils" / "assertions.cpp",
            gen_path / "utils" / "png.cpp",
            gen_path / "built_in" / "type_id.cpp",
        ]
        # Also include native C++ implementations for extern runtime modules.
        # Exclude files that conflict with conftest-generated headers.
        native_exclude = {"glob.cpp"}  # glob.cpp uses Object<list<str>> but conftest header uses rc<list<str>>
        native_cpp_root = Path("src/runtime/cpp")
        for subdir in ["std", "utils"]:
            native_dir = native_cpp_root / subdir
            if native_dir.exists():
                for cpp_file in sorted(native_dir.glob("*.cpp")):
                    if cpp_file.name not in native_exclude:
                        needed.append(cpp_file)
        return [str(f) for f in needed if f.exists()]

    manifest = _load_manifest(manifest_path)
    module_sources = _collect_sources(manifest)

    include_dir_obj = manifest.get("include_dir")
    include_dir = include_dir_obj if isinstance(include_dir_obj, str) else str(manifest_path.parent / "include")
    include_dir_path = Path(include_dir)
    if not include_dir_path.is_absolute():
        include_dir_path = (manifest_path.parent / include_dir_path).resolve()

    cmd = [
        "g++",
        f"-std={args.std}",
        args.opt,
        "-I",
        "src",
        "-I",
        "src/runtime/cpp",
        "-I",
        "src/runtime/east",
        "-I",
        str(include_dir_path),
        "-I",
        os.environ.get("PYTRA_GENERATED_CPP_DIR", "out/_test_generated_cpp"),
        *module_sources,
        *collect_runtime_cpp_sources(module_sources, include_dir_path),
        *_collect_generated_cpp_sources(),
        "-o",
        args.output,
    ]
    p = subprocess.run(cmd)
    return int(p.returncode)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
